version: '3.3'
services:
  web:
    image: nestlae/swarm01-web:110323
    networks:
      - webproxy
    logging:
      driver: json-file
    volumes:
      - app:/var/www/html/
    container_name: apache2-php
    deploy:
      replicas: 1
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.${APPNAME}-https.entrypoints=websecure
        - traefik.http.routers.${APPNAME}-https.rule=Host("${APPNAME}.xops.ipv9.xyz")
        - traefik.http.routers.${APPNAME}-https.tls.certresolver=default
        - traefik.http.services.${APPNAME}.loadbalancer.server.port=80
      resources:
        reservations:
          cpus: '0.1'
          memory: 10M
        limits:
          cpus: '0.4'
          memory: 50M

volumes:
  app:

networks:
  webproxy:
    external: true